server:
  host: 0.0.0.0
  port: 8080

logging:
  filename: sonic.log
  level:
    app: debug #  debug,info,warn,error
    gorm: info #  info,warn,error,silent
  maxsize: 10 # 单位 megabytes
  maxage: 30 #单位 天
  compress: false # 是否对旧日志使用gzip进行压缩


### 数据库配置， MySQL 和 SQLite3 二选一 .如果同时配置了MySQL 或 SQLite3 ，优先使用 Sqlite3
### The Database configuration,You should choose one between MySQL and SQLite3,if both MySQL and SQLite3 are configured ,use Sqlite3 first

sqlite3:
  enable: true

### mysql数据库配置,请将用户名、密码、ip地址、端口、数据库名称替换为你自己的配置
### mysql database configuration, please replace the user name, password, ip address, port, database name to your own configuration.
mysql:
  dsn: root:12345678@tcp(127.0.0.1:3306)/sonicdb?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true



sonic:
  mode: "development"
  work_dir: "./" # 不填默认为当前路径，用来存放日志文件、数据库文件、模板、上传的附件等(The default is the current directory. Used to store log files, database files, templates, upload files)
  log_dir: "./logs" # 不填则使用work_dir 路径下的log路径 (If it is empty, use the "log" path under work_dir)
  admin_url_path: admin_random